@echo off
echo stopping and removing redis node1.... 
docker stop node1  && docker rm node1 
echo stopping and removing redis node2.... 
docker stop node2  && docker rm node2 
echo stopping and removing redis node3.... 
docker stop node3  && docker rm node3
